name = "otter-valley-app"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 22 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "otter-valley-app-db"
database_id = "2d17cac2-5c0d-46a6-9096-0145570de15f"

[vars]
CLUB_EMAIL = "ovrag@hotmail.com"
APP_NAME = "Otter Valley R&G Club"
